version: "3.4"

services:

  dev:
    build:
      context: .
      target: base
    volumes:
      - .:/app
      - node-10-modules-cache:/app/node_modules
    working_dir: /app
    entrypoint: /app/scripts/yarn-exec
    command: bash

volumes:
  node-10-modules-cache: ~
